### PR TITLE
Check for uninitialized group

### LINKED ISSUE #575: User Constructor not called on login. groups not being initialized
## Subject
I upgraded my symfony project from 4.x to 5.x along with PHP 7.4 to 8.0. This was a month back or so and I had no issues with the login. Today my login just didn't work. No error, I just couldn't log in with any user. No idea what was going on. I was using Nucleos v1.3, so I figured I upgrade it to v2. Maybe this will work better with PHP 8 and symfony 5. 
When I tried to log in I got the following error:
"Typed property Nucleos\UserBundle\Model\User::$groups must not be accessed before initialization"

As a work-around I overwrote getGroups() and simply returned an empty ArrayCollection as I do not use groups in my project.
It seems the constructor of my User object is not called. And therefore the groups property is not initialized when the UserAuthenticateProvider calls $user->getRoles() which also uses the groups. 

#### Packages

```
doctrine/annotations                 1.13.2    1.13.2    Docblock Annotations Parser
doctrine/cache                       2.1.1     2.1.1     PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and ot...
doctrine/collections                 1.6.8     1.6.8     PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                      3.2.1     3.2.1     PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflecti...
doctrine/data-fixtures               1.5.1     1.5.2     Data Fixtures for all Doctrine Object Managers
doctrine/dbal                        3.3.0     3.3.0     Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/deprecations                v0.5.3    v0.5.3    A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all deprecations or selectively for packages.
doctrine/doctrine-bundle             2.5.5     2.5.5     Symfony DoctrineBundle
doctrine/doctrine-fixtures-bundle    3.4.1     3.4.1     Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle  3.2.1     3.2.1     Symfony DoctrineMigrationsBundle
doctrine/event-manager               1.1.1     1.1.1     The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                   2.0.4     2.0.4     PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of wo...
doctrine/instantiator                1.4.0     1.4.0     A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       1.2.2     1.2.2     PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                  3.4.0     3.4.0     PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database sc...
doctrine/orm                         2.11.0    2.11.0    Object-Relational-Mapper for PHP
doctrine/persistence                 2.3.0     2.3.0     The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/sql-formatter               1.1.2     1.1.2     a PHP SQL highlighting library
egulias/email-validator              3.1.2     3.1.2     A library for validating emails against several RFCs
friendsofphp/proxy-manager-lts       v1.0.5    v1.0.5    Adding support for a wider range of PHP versions to ocramius/proxy-manager
imagine/imagine                      1.2.4     1.2.4     Image processing for PHP 5.3
jms/translation-bundle               1.6.1     1.6.1     Puts the Symfony Translation Component on steroids
laminas/laminas-code                 4.5.1     4.5.1     Extensions to the PHP Reflection API, static code scanning, and code generation
league/flysystem                     1.1.9     3.0.1     Filesystem abstraction: Many filesystems, one API.
league/mime-type-detection           1.9.0     1.9.0     Mime-type detection for Flysystem
liip/imagine-bundle                  2.7.6     2.7.6     This bundle provides an image manipulation abstraction toolkit for Symfony-based projects.
myclabs/deep-copy                    1.10.2    1.10.2    Create deep copies (clones) of your objects
nikic/php-parser                     v4.13.2   v4.13.2   A PHP parser written in PHP
nucleos/user-bundle                  2.0.0     2.0.0     Lightweight user management for symfony
oneup/flysystem-bundle               3.7.1     4.3.0     Integrates Flysystem filesystem abstraction library to your Symfony project.
oneup/uploader-bundle                3.1.3     3.1.3     This Symfony bundle provides a server implementation for handling single and multiple file uploads using either FineUploader, jQuery File Uplo...
phar-io/manifest                     2.0.3     2.0.3     Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                      3.1.0     3.1.0     Library for handling version information and constraints
phpdocumentor/reflection-common      2.2.0     2.2.0     Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock    5.3.0     5.3.0     With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBl...
phpdocumentor/type-resolver          1.6.0     1.6.0     A PSR-5 based resolver of Class names, Types and Structural Element Names
phpspec/prophecy                     v1.15.0   v1.15.0   Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage            9.2.10    9.2.10    Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator            3.0.6     3.0.6     FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                  3.1.1     3.1.1     Invoke callables with a timeout
phpunit/php-text-template            2.0.4     2.0.4     Simple template engine.
phpunit/php-timer                    5.0.3     5.0.3     Utility class for timing
phpunit/phpunit                      9.5.11    9.5.13    The PHP Unit Testing framework.
psr/cache                            2.0.0     3.0.0     Common interface for caching libraries
psr/container                        1.1.2     2.0.2     Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                 1.0.0     1.0.0     Standard interfaces for event handling.
psr/link                             1.1.1     2.0.1     Common interfaces for HTTP links
psr/log                              2.0.0     3.0.0     Common interface for logging libraries
sebastian/cli-parser                 1.0.1     1.0.1     Library for parsing CLI options
sebastian/code-unit                  1.0.8     1.0.8     Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup   2.0.3     2.0.3     Looks up which function or method a line of code belongs to
sebastian/comparator                 4.0.6     4.0.6     Provides the functionality to compare PHP values for equality
sebastian/complexity                 2.0.2     2.0.2     Library for calculating the complexity of PHP code units
sebastian/diff                       4.0.4     4.0.4     Diff implementation
sebastian/environment                5.1.3     5.1.3     Provides functionality to handle HHVM/PHP environments
sebastian/exporter                   4.0.4     4.0.4     Provides the functionality to export PHP variables for visualization
sebastian/global-state               5.0.3     5.0.3     Snapshotting of global state
sebastian/lines-of-code              1.0.3     1.0.3     Library for counting the lines of code in PHP source code
sebastian/object-enumerator          4.0.4     4.0.4     Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector           2.0.4     2.0.4     Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context          4.0.4     4.0.4     Provides functionality to recursively process PHP variables
sebastian/resource-operations        3.0.3     3.0.3     Provides a list of PHP built-in functions that operate on resources
sebastian/type                       2.3.4     2.3.4     Collection of value objects that represent the types of the PHP type system
sebastian/version                    3.0.2     3.0.2     Library that helps with managing the version number of Git-hosted PHP projects
sensio/framework-extra-bundle        v5.6.1    v6.2.6    This bundle provides a way to configure your controllers with annotations
symfony/apache-pack                  v1.0.1    v1.0.1    A pack for Apache support in Symfony
symfony/asset                        v5.4.0    v6.0.3    Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/browser-kit                  v5.4.2    v6.0.3    Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/cache                        v5.4.3    v6.0.3    Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts              v2.5.0    v3.0.0    Generic abstractions related to caching
symfony/config                       v5.4.3    v6.0.3    Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                      v5.4.3    v6.0.3    Eases the creation of beautiful and testable command line interfaces
symfony/css-selector                 v5.4.2    v6.0.3    Converts CSS selectors to XPath expressions
symfony/debug-bundle                 v5.4.2    v6.0.3    Provides a tight integration of the Symfony VarDumper component and the ServerLogCommand from MonologBridge into the Symfony full-stack framework
symfony/dependency-injection         v5.4.3    v6.0.3    Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts        v3.0.0    v3.0.0    A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge              v5.4.2    v6.0.3    Provides integration for Doctrine with various Symfony components
symfony/dom-crawler                  v5.4.2    v6.0.3    Eases DOM navigation for HTML and XML documents
symfony/dotenv                       v5.4.2    v6.0.3    Registers environment variables from a .env file
symfony/error-handler                v5.4.3    v6.0.3    Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher             v5.4.3    v6.0.3    Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts   v2.5.0    v3.0.0    Generic abstractions related to dispatching event
symfony/expression-language          v5.4.0    v6.0.3    Provides an engine that can compile and evaluate expressions
symfony/filesystem                   v5.4.3    v6.0.3    Provides basic utilities for the filesystem
symfony/finder                       v5.4.3    v6.0.3    Finds files and directories via an intuitive fluent interface
symfony/flex                         v2.1.2    v2.1.4    Composer plugin for Symfony
symfony/form                         v5.4.3    v6.0.3    Allows to easily create, process and reuse HTML forms
symfony/framework-bundle             v5.4.3    v6.0.3    Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                  v5.4.2    v6.0.3    Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts        v2.5.0    v3.0.0    Generic abstractions related to HTTP clients
symfony/http-foundation              v5.4.3    v6.0.3    Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                  v5.4.3    v6.0.3    Provides a structured process for converting a Request into a Response
symfony/intl                         v5.4.3    v6.0.3    Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mailer                       v5.4.3    v6.0.3    Helps sending emails
symfony/maker-bundle                 v1.36.4   v1.36.4   Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mime                         v5.4.3    v6.0.3    Allows manipulating MIME messages
symfony/options-resolver             v5.4.3    v6.0.3    Provides an improved replacement for the array_replace PHP function
symfony/password-hasher              v5.4.3    v6.0.3    Provides password hashing utilities
symfony/phpunit-bridge               v5.4.0    v6.0.3    Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-intl-grapheme       v1.24.0   v1.24.0   Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu            v1.24.0   v1.24.0   Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn            v1.24.0   v1.24.0   Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer     v1.24.0   v1.24.0   Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring            v1.24.0   v1.24.0   Symfony polyfill for the Mbstring extension
symfony/polyfill-php72               v1.24.0   v1.24.0   Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73               v1.24.0   v1.24.0   Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80               v1.24.0   v1.24.0   Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81               v1.24.0   v1.24.0   Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/process                      v5.4.2    v6.0.3    Executes commands in sub-processes
symfony/property-access              v5.4.3    v6.0.3    Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info                v5.4.3    v6.0.3    Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge         v5.4.2    v6.0.3    Provides integration for ProxyManager with various Symfony components
symfony/routing                      v5.4.3    v6.0.3    Maps an HTTP request to a set of configuration variables
symfony/runtime                      v5.4.1    v6.0.3    Enables decoupling PHP applications from global state
symfony/security-bundle              v5.4.3    v6.0.3    Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core                v5.4.3    v6.0.3    Symfony Security Component - Core Library
symfony/security-csrf                v5.4.3    v6.0.3    Symfony Security Component - CSRF Library
symfony/security-guard               v5.4.3    v5.4.3    Symfony Security Component - Guard
symfony/security-http                v5.4.3    v6.0.3    Symfony Security Component - HTTP Integration
symfony/serializer                   v5.4.2    v6.0.3    Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/service-contracts            v2.4.1    v3.0.0    Generic abstractions related to writing services
symfony/stopwatch                    v5.4.0    v6.0.3    Provides a way to profile code
symfony/string                       v5.4.3    v6.0.3    Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/templating                   v5.4.0    v6.0.3    Provides all the tools needed to build any kind of template system
symfony/translation                  v5.4.3    v6.0.3    Provides tools to internationalize your application
symfony/translation-contracts        v2.5.0    v3.0.0    Generic abstractions related to translation
symfony/twig-bridge                  v5.4.3    v6.0.3    Provides integration for Twig with various Symfony components
symfony/twig-bundle                  v5.4.3    v6.0.3    Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                    v5.4.3    v6.0.3    Provides tools to validate values
symfony/var-dumper                   v5.4.3    v6.0.3    Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter                 v5.4.3    v6.0.3    Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                     v5.4.0    v6.0.3    Manages links between resources
symfony/web-profiler-bundle          v5.4.2    v6.0.3    Provides a development tool that gives detailed information about the execution of any request
symfony/webpack-encore-bundle        v1.13.2   v1.13.2   Integration with your Symfony app & Webpack Encore!
symfony/workflow                     v5.4.2    v6.0.3    Provides tools for managing a workflow or finite state machine
symfony/yaml                         v5.4.2    v6.0.3    Loads and dumps YAML files
theseer/tokenizer                    1.2.1     1.2.1     A small library for converting tokenized PHP source code into XML and potentially other formats
twig/extra-bundle                    v3.3.7    v3.3.7    A Symfony bundle for extra Twig extensions
twig/twig                            v3.3.7    v3.3.7    Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                     1.10.0    1.10.0    Assertions to validate method input/output with nice error messages.
```

#### PHP version

```
PHP 8.0.8 (cli) (built: Sep 30 2021 13:54:04) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.8, Copyright (c) Zend Technologies
    with Xdebug v3.0.3, Copyright (c) 2002-2021, by Derick Rethans
```

### PR DESCRIPTION
**Pull request by core23**
Closes #575

## Subject

Allow accessing groups without group feature

### CODE REVIEW

**Comment by core23** [comment]
I think I could reproduce your case. Can you please check this @seizan8?

**Comment by seizan8** [comment]
Yes, seems to work fine now. I still don't understand why groups property is null though. 
Thanks

**Comment by core23** [comment]
Doctrine does not use constructors for entity creation, so the property does not have a valid default value.

**Comment by seizan8** [comment]
So.... the property is not hydrated properly or what?

If I load any other entity they have an empty ArrayCollection set. So either the constructor has to be called or an empty ArrayCollection was set with a setter.

**Pull request merged**
