### PR TITLE
Bump to symfony ^6.4 || ^7.0

### PR DESCRIPTION
**Pull request by core23**

### CODE REVIEW

**Comment by core23** [comment]
Depends on https://github.com/doctrine/DoctrineMongoDBBundle/pull/784

**Comment by Guite** [comment]
> Depends on [doctrine/DoctrineMongoDBBundle#784](https://github.com/doctrine/DoctrineMongoDBBundle/pull/784)

Still blocked?

**Comment by core23** [comment]
> > Depends on [doctrine/DoctrineMongoDBBundle#784](https://github.com/doctrine/DoctrineMongoDBBundle/pull/784)
> 
> Still blocked?

Yes, because the PR targets the upcoming 5.x release :(

**Comment by Guite** [comment]
Seems #737 is what is needed here.

**Pull request merged**
