### PR TITLE
doctrine/common dependency update for Symfony 5.1

### LINKED ISSUE #102: Installation problem on brand new Symfony 5.1.x
### Environment
MacOS 10.15.7, nginx 1.19.3, php 7.4.10, mariadb 10.5.6

#### Packages

```
$ composer show --latest
Restricting packages listed in "symfony/symfony" to "5.1.*"
composer/package-versions-deprecated 1.11.99 1.11.99 Composer plugin that provides efficient querying for installed package versions (no...
doctrine/annotations                 1.10.4  1.10.4  Docblock Annotations Parser
doctrine/cache                       1.10.2  1.10.2  PHP Doctrine Cache library is a popular cache implementation that supports many dif...
doctrine/collections                 1.6.7   1.6.7   PHP Doctrine Collections library that adds additional functionality on top of PHP a...
doctrine/common                      3.0.2   3.0.2   PHP Doctrine Common project is a library that provides additional functionality tha...
doctrine/dbal                        2.11.1  2.11.1  Powerful PHP database abstraction layer (DBAL) with many features for database sche...
doctrine/doctrine-bundle             2.1.2   2.1.2   Symfony DoctrineBundle
doctrine/doctrine-migrations-bundle  3.0.1   3.0.1   Symfony DoctrineMigrationsBundle
doctrine/event-manager               1.1.1   1.1.1   The Doctrine Event Manager is a simple PHP event system that was built to be used w...
doctrine/inflector                   1.4.3   2.0.3   PHP Doctrine Inflector is a small library that can perform string manipulations wit...
doctrine/instantiator                1.3.1   1.3.1   A small, lightweight utility to instantiate objects in PHP without invoking their c...
doctrine/lexer                       1.2.1   1.2.1   PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent P...
doctrine/migrations                  3.0.1   3.0.1   PHP Doctrine Migrations project offer additional functionality on top of the databa...
doctrine/orm                         2.7.4   2.7.4   Object-Relational-Mapper for PHP
doctrine/persistence                 2.0.0   2.0.0   The Doctrine Persistence project is a set of shared interfaces and functionality th...
doctrine/reflection                  1.2.1   1.2.1   The Doctrine Reflection project is a simple library used by the various Doctrine pr...
doctrine/sql-formatter               1.1.1   1.1.1   a PHP SQL highlighting library
friendsofsymfony/rest-bundle         3.0.3   3.0.3   This Bundle provides various tools to rapidly develop RESTful API's with Symfony
laminas/laminas-code                 3.4.1   3.4.1   Extensions to the PHP Reflection API, static code scanning, and code generation
laminas/laminas-eventmanager         3.3.0   3.3.0   Trigger and listen to events within a PHP application
laminas/laminas-zendframework-bridge 1.1.1   1.1.1   Alias legacy ZF class names to Laminas Project equivalents.
ocramius/proxy-manager               2.8.0   2.8.1   A library providing utilities to generate, instantiate and generally operate with O...
phpdocumentor/reflection-common      2.2.0   2.2.0   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock    5.2.2   5.2.2   With this component, a library can provide support for annotations via DocBlocks or...
phpdocumentor/type-resolver          1.4.0   1.4.0   A PSR-5 based resolver of Class names, Types and Structural Element Names
psr/cache                            1.0.1   1.0.1   Common interface for caching libraries
psr/container                        1.0.0   1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                 1.0.0   1.0.0   Standard interfaces for event handling.
psr/log                              1.1.3   1.1.3   Common interface for logging libraries
symfony/cache                        v5.1.7  v5.1.7  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts              v2.2.0  v2.2.0  Generic abstractions related to caching
symfony/config                       v5.1.7  v5.1.7  Symfony Config Component
symfony/console                      v5.1.7  v5.1.7  Symfony Console Component
symfony/dependency-injection         v5.1.7  v5.1.7  Symfony DependencyInjection Component
symfony/deprecation-contracts        v2.2.0  v2.2.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge              v5.1.7  v5.1.7  Symfony Doctrine Bridge
symfony/dotenv                       v5.1.7  v5.1.7  Registers environment variables from a .env file
symfony/error-handler                v5.1.7  v5.1.7  Symfony ErrorHandler Component
symfony/event-dispatcher             v5.1.7  v5.1.7  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts   v2.2.0  v2.2.0  Generic abstractions related to dispatching event
symfony/filesystem                   v5.1.7  v5.1.7  Symfony Filesystem Component
symfony/finder                       v5.1.7  v5.1.7  Symfony Finder Component
symfony/flex                         v1.9.6  v1.9.6  Composer plugin for Symfony
symfony/framework-bundle             v5.1.7  v5.1.7  Symfony FrameworkBundle
symfony/http-client-contracts        v2.2.0  v2.2.0  Generic abstractions related to HTTP clients
symfony/http-foundation              v5.1.7  v5.1.7  Symfony HttpFoundation Component
symfony/http-kernel                  v5.1.7  v5.1.7  Symfony HttpKernel Component
symfony/polyfill-intl-grapheme       v1.18.1 v1.18.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer     v1.18.1 v1.18.1 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring            v1.18.1 v1.18.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73               v1.18.1 v1.18.1 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80               v1.18.1 v1.18.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/property-access              v5.1.7  v5.1.7  Symfony PropertyAccess Component
symfony/property-info                v5.1.7  v5.1.7  Symfony Property Info Component
symfony/routing                      v5.1.7  v5.1.7  Symfony Routing Component
symfony/security-core                v5.1.7  v5.1.7  Symfony Security Component - Core Library
symfony/serializer                   v5.1.7  v5.1.7  Symfony Serializer Component
symfony/service-contracts            v2.2.0  v2.2.0  Generic abstractions related to writing services
symfony/stopwatch                    v5.1.7  v5.1.7  Symfony Stopwatch Component
symfony/string                       v5.1.7  v5.1.7  Symfony String component
symfony/translation-contracts        v2.3.0  v2.3.0  Generic abstractions related to translation
symfony/twig-bridge                  v5.1.7  v5.1.7  Symfony Twig Bridge
symfony/twig-bundle                  v5.1.7  v5.1.7  Symfony TwigBundle
symfony/var-dumper                   v5.1.7  v5.1.7  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                 v5.1.7  v5.1.7  A blend of var_export() + serialize() to turn any serializable data structure to pl...
symfony/web-profiler-bundle          v5.1.7  v5.1.7  Symfony WebProfilerBundle
symfony/yaml                         v5.1.7  v5.1.7  Symfony Yaml Component
twig/twig                            v3.0.5  v3.0.5  Twig, the flexible, fast, and secure template language for PHP
webimpress/safe-writer               2.1.0   2.1.0   Tool to write files safely, to avoid race conditions
webmozart/assert                     1.9.1   1.9.1   Assertions to validate method input/output with nice error messages.
willdurand/jsonp-callback-validator  v1.1.0  v1.1.0  JSONP callback validator.
willdurand/negotiation               v2.3.1  v2.3.1  Content Negotiation tools for PHP provided as a standalone library.
```

#### PHP version

```
$ php -v
PHP 7.4.11 (cli) (built: Oct  1 2020 23:30:54) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies
```
## Steps to reproduce

composer require nucleos/user-bundle

## Actual results
```
Using version ^1.4 for nucleos/user-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.1.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nucleos/user-bundle ^1.4 -> satisfiable by nucleos/user-bundle[1.4.0].
    - Conclusion: remove doctrine/common 3.0.2
    - Conclusion: don't install doctrine/common 3.0.2
    - nucleos/user-bundle 1.4.0 requires doctrine/common ^2.11 -> satisfiable by doctrine/common[2.12.0, 2.13.0, 2.13.1, 2.13.2, 2.13.3, v2.11.0].
    - Can only install one of: doctrine/common[2.12.0, 3.0.2].
    - Can only install one of: doctrine/common[2.13.0, 3.0.2].
    - Can only install one of: doctrine/common[2.13.1, 3.0.2].
    - Can only install one of: doctrine/common[2.13.2, 3.0.2].
    - Can only install one of: doctrine/common[2.13.3, 3.0.2].
    - Can only install one of: doctrine/common[v2.11.0, 3.0.2].
    - Installation request for doctrine/common (locked at 3.0.2) -> satisfiable by doctrine/common[3.0.2].


Installation failed, reverting ./composer.json to its original content.
```

### PR DESCRIPTION
**Pull request by droM4X**
Closes #102

## Subject

doctrine/common dependency update for Symfony 5.1

### CODE REVIEW

**Comment by core23** [comment]
Please have a look at the CI: https://github.com/nucleos/NucleosUserBundle/pull/103/checks?check_run_id=1239483935#step:8:91

The new dependency can't be resolved.

**Comment by droM4X** [comment]
I see but I dont know why dont use the latest version.

I tried again, with symfony cli + some basic package: doctrine/orm and doctrine-bundle, and as I see doctrine/orm installed the doctrine/common 3.0.2:
```
bash-3.2$ symfony new test
* Creating a new Symfony project with Composer
  (running /usr/local/bin/composer create-project symfony/skeleton /var/www/test)

* Setting up the project under Git version control
  (running git init /var/www/test)


 [OK] Your project is now ready in /var/www/test


bash-3.2$ cd test
bash-3.2$ ls
bin		composer.lock	public		symfony.lock	vendor
composer.json	config		src		var
bash-3.2$ composer require doctrine/orm
Using version ^2.7 for doctrine/orm
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.1.*"
Package operations: 13 installs, 0 updates, 0 removals
  - Installing composer/package-versions-deprecated (1.11.99): Loading from cache
  - Installing doctrine/lexer (1.2.1): Loading from cache
  - Installing doctrine/annotations (1.10.4): Loading from cache
  - Installing doctrine/reflection (1.2.1): Loading from cache
  - Installing doctrine/event-manager (1.1.1): Loading from cache
  - Installing doctrine/collections (1.6.7): Loading from cache
  - Installing doctrine/cache (1.10.2): Loading from cache
  - Installing doctrine/persistence (2.0.0): Loading from cache
  - Installing doctrine/instantiator (1.3.1): Loading from cache
  - Installing doctrine/inflector (1.4.3): Loading from cache
  - Installing doctrine/dbal (2.11.1): Loading from cache
  - Installing doctrine/common (3.0.2): Loading from cache
  - Installing doctrine/orm (2.7.4): Loading from cache
Writing lock file
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
37 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Symfony operations: 1 recipe (6b4386a6a9017822738f81f118d5b558)
  - Configuring doctrine/annotations (>=1.0): From github.com/symfony/recipes:master
Executing script cache:clear [OK]
Executing script assets:install public [OK]

Some files may have been created or updated to configure your new packages.
Please review, edit and commit them: these files are yours.

Nothing to unpack
bash-3.2$ composer require doctrine/doctrine-bundle
Using version ^2.1 for doctrine/doctrine-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.1.*"
Package operations: 3 installs, 0 updates, 0 removals
  - Installing symfony/doctrine-bridge (v5.1.7): Loading from cache
  - Installing doctrine/sql-formatter (1.1.1): Loading from cache
  - Installing doctrine/doctrine-bundle (2.1.2): Loading from cache
Writing lock file
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
39 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Symfony operations: 1 recipe (da6f63b3afe261a4cc9917bb07039114)
  - Configuring doctrine/doctrine-bundle (>=2.0): From github.com/symfony/recipes:master
Executing script cache:clear [OK]
Executing script assets:install public [OK]

Some files may have been created or updated to configure your new packages.
Please review, edit and commit them: these files are yours.


 Database Configuration


  * Modify your DATABASE_URL config in .env

  * Configure the driver (mysql) and
    server_version (5.7) in config/packages/doctrine.yaml

Nothing to unpack
bash-3.2$ composer require nucleos/user-bundle
Using version ^1.4 for nucleos/user-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.1.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nucleos/user-bundle ^1.4 -> satisfiable by nucleos/user-bundle[1.4.0].
    - Conclusion: remove doctrine/common 3.0.2
    - Conclusion: don't install doctrine/common 3.0.2
    - nucleos/user-bundle 1.4.0 requires doctrine/common ^2.11 -> satisfiable by doctrine/common[2.12.0, 2.13.0, 2.13.1, 2.13.2, 2.13.3, v2.11.0].
    - Can only install one of: doctrine/common[2.12.0, 3.0.2].
    - Can only install one of: doctrine/common[2.13.0, 3.0.2].
    - Can only install one of: doctrine/common[2.13.1, 3.0.2].
    - Can only install one of: doctrine/common[2.13.2, 3.0.2].
    - Can only install one of: doctrine/common[2.13.3, 3.0.2].
    - Can only install one of: doctrine/common[v2.11.0, 3.0.2].
    - Installation request for doctrine/common (locked at 3.0.2) -> satisfiable by doctrine/common[3.0.2].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by core23** [comment]
Can you please try to debug the versions with `composer why-not some-vendor/dependeny-name`

**Comment by TorbenLundsgaard** [comment]
```
why-not doctrine/common 3
doctrine/mongodb     1.6.4    requires  doctrine/common (^2.2)       
doctrine/common      3.0.0    requires  doctrine/persistence (^2.0)  
nucleos/user-bundle  1.x-dev  requires  doctrine/persistence (^1.3)

```
The doctrine/mongodb library is deprecated and will not support doctrine/common 3. So it looks like it needs to be dropped in order to move forward

**Comment by core23** [comment]
I'm okay with dropping support for mongo db in this bundle if this will be a problem in the future. Is there any other solution with https://github.com/mongodb/mongo-php-library?

**Comment by core23** [comment]
AFAIK the latest doctrine odm version does not need this dependency anymore, maybe we can migrate the code.

**Comment by TorbenLundsgaard** [comment]
You are right. mongodb-odm-bundle requires mongodb-odm 2, which uses ext-mongodb, so mongodb-odm 1 and mongodb are not used and can be dropped

**Comment by core23** [comment]
Still using `doctrine/common` 2 with the latest update :/

**Comment by TorbenLundsgaard** [comment]
That's because we need to allow doctrine/persistence 2. I will take a look at it later

**Pull request closed without merging**
